#ifndef MICROPY_INCLUDED_SHARED_BINDINGS_DIGIT_CLASSIFIER_H
#define MICROPY_INCLUDED_SHARED_BINDINGS_DIGIT_CLASSIFIER_H

void entry(const float tensor_input[1][30][30][1], float tensor_output[1][10]);

#endif // MICROPY_INCLUDED_SHARED_BINDINGS_DIGIT_CLASSIFIER_H